FROM public.ecr.aws/lambda/python:3.10

USER root

COPY ./.ssh/authorized_keys /root/.ssh/authorized_keys

RUN yum -y update

RUN yum -y install openssh-server openssh-clients
RUN yum -y install sudo
RUN yum -y install rsync
RUN yum -y install which
RUN yum -y install tar

# <DEBUGGING>
RUN yum -y install nano
RUN yum -y install htop
# </DEBUGGING>

ENV SSH_USER docker
ENV SSH_PASSWORD docker
ENV SSH_USER_WD /home/$SSH_USER

COPY ./.ssh/authorized_keys $SSH_USER_WD/.ssh/authorized_keys

RUN sudo useradd -m -s /bin/bash $SSH_USER && \
    sudo echo "$SSH_USER:$SSH_PASSWORD" | sudo chpasswd

RUN sudo chown docker /etc/ssh/sshd_config
RUN sudo chmod 644 /etc/ssh/sshd_config
RUN sudo chown docker /etc/ssh
RUN sudo chmod 775 /etc/ssh
RUN sudo chown docker /var/task
RUN sudo chmod 775 /var/task
RUN sudo chown docker $SSH_USER_WD
RUN sudo chmod 755 $SSH_USER_WD
RUN sudo chown docker $SSH_USER_WD/.ssh
RUN sudo chmod 700 $SSH_USER_WD/.ssh
RUN sudo chown docker $SSH_USER_WD/.ssh/authorized_keys
RUN sudo chmod 600 $SSH_USER_WD/.ssh/authorized_keys
RUN sudo usermod -aG root docker


RUN echo "export PATH=$PATH:/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin" >> $SSH_USER_WD/.bashrc
RUN echo "alias ll='ls -alF'" >> $SSH_USER_WD/.bashrc
RUN echo "alias la='ls -A'" >> $SSH_USER_WD/.bashrc
RUN echo "alias l='ls -CF'" >> $SSH_USER_WD/.bashrc
RUN echo "export LAMBDA_TASK_ROOT=/var/task" >> $SSH_USER_WD/.bashrc
RUN echo "export LD_LIBRARY_PATH=/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib" >> $SSH_USER_WD/.bashrc
RUN echo "export LAMBDA_RUNTIME_DIR=/var/runtime" >> $SSH_USER_WD/.bashrc
RUN echo "export PYTHONPATH=/var/runtime" >> $SSH_USER_WD/.bashrc

#USER docker
RUN ssh-keygen -A

WORKDIR $LAMBDA_TASK_ROOT

ENTRYPOINT ["/usr/sbin/sshd"]
CMD ["-D"]